## Функции. Рекурсия.


### Упражение 1
Написать функцию, считающую N-ое число Фибоначчи (N вводится с клавиатуры).

In [3]:
def f(n):
    if n == 1 or n == 2:
        return 1
    return f(n-1)+f(n-2)

n = int(input())
print(f(n))

 4


3


### Упражение 2
Написать функцию, раскладывающую число на простые множители (число вводится с клавиатуры).

In [ ]:
def f(n):
    if n == 0:
        return(0)
    i = 2
    a = []
    while i <= (n**0.5)+1:
        while n % i == 0:
            a.append(i + f(n-n))
            n = n // i
        i = i + 1
    if n > 1:
        a.append(n)
    return a

n = int(input())
print(*f(n))

### Упражнение 3
Со времен Евклида известно, что для любых положительных a и b существуют такие целые x и y, что ax + by = d, где d – наибольший общий делитель a и b. По заданным a и b найти x, y, d.

Вход. Каждая строка содержит два натуральных числа a и b, разделенных пробелом.

Выход. Для каждой пары a и b в отдельной строке вывести три целых числа x, y и d, разделенных пробелом. Если искомых значений x и y несколько, то следует выводить такую пару, для которой |x| + |y| минимально. Если и таких пар несколько, то вывести ту пару, в которой x минимально.

|Пример входа|Пример выхода|
|-|-|
|4 6|-1 1 2|
|17 17|0 1 17|
|5 3|-1 2 1|

In [4]:
def f(n):
    if n == 0:
        return 0
    i = 2
    a = []
    while i <= (n**0.5)+1:
        while n % i == 0:
            a.append(i + f(n-n))
            n = n // i
        i = i + 1
    if n > 1:
        a.append(n)
    return a

a, b = map(int, input().split())
d1 = f(a)
d2 = f(b)
m = []
for i in d1:
    if i in d2:
        m.append(i)
        d2.pop(d2.index(i))
ans = 1
for j in m:
    ans *= j
for i in range(100):
    y = (ans - a*i)/b
    y1 = (ans + a*i)/b
    if y == int(y):
        print(i, (ans - a*i)//b, ans)
        break
    if y1 == int(y1):
        print(-i, (ans + a*i)//b, ans)
        break

 1 3


1 0 1


### Упражнение 4
Напишите функцию для вывода треугольника. Функция принимает два аргумента – size (количество строк, на которых будет строиться треугольник) и symb (символ, используемый для заполнения треугольника).

Пример входа: `7 c`

Пример выхода:
![image-2.png](attachment:image-2.png) 

In [ ]:
n, s = map(str, input().split())
n = int(n)
if n%2!=0:
    k1 = n//2+1
    k2 = k1-1
else:
    k1 = n//2
    k2 = k1
for i in range(1, k1+1):
    print(s*i)
for i in range(k2, 0, -1):
    print(s*i)

## Библиотеки. Numpy

Для решения практических задач часто бывает необходимо 
Для вычисления математических функций в python есть стандартная библиотека [math](http://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html#numpy.log). Однако значительно более сильным инструментом является библиотека [numpy](http://docs.scipy.org/doc/numpy/reference/generated/numpy.polyfit.html).
Данная библиотека обеспечивает удобную работу с векторами, которые здесь наззываются массивами (arrays).

Т.е., если у нас есть массив X и мы вызовем numpy.log(x), то логарифм будет взят от каждого элемента и возвращен будет массив значений логарифмов элементов.

Традиционно библиотека numpy (как и любая другая) подключается командой:

``` python
import numpy
```
Пример вызова функции из библиотеки
``` python
numpy.cos(x)
```
Библиотеки можно подключить под псевдонимом:
``` python
import numpy as np
```
В таком случае мы можем вызывать функции так:
``` python
np.cos(x)
```
Такой код значительно проще читать и писать.

Возможно также подключать отдельные функции из библиотеки, это позволит вызывать их без указания названия библиотеки:
``` python
from numpy import cos
cos(x)
```
``` python
from numpy import cos
cos(x)
```

Как уже было сказано, основной объект, с которым принято взаимодействовать в numpy -- массивы. Они отличаются от списков тем, что могут хранить значения, имеющие один и тот же тип, и имеют определенные по-другому операции. Например:

``` python
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a + b
```
Если бы `a` и `b` были списками, то мы получили бы "сшитый" список. Однако в данном случае мы получим результат поэлементного сложения двух массивов.

### *Broadcasting

Одной из фишек библиотеки numpy является [бродкастинг](https://numpy.org/doc/stable/user/basics.broadcasting.html). Он позволяет существенно упростить многие операции с массивами и матрицами. Самый простой пример бродкастинга:
```python
a = np.array([1,2,3,4])
b = 1
c = a + b
```
Казалось бы, мы должны получить ошибку, ведь массив и число -- разные типы данных. Однако в данном случае numpy поймет, что вы хотите прибавить единицу ко всем элементам массива и сделает это. Аналогично можно прибавлять к матрице вектор или строку соответствующего размера.

### Упражнение 5

Создайте матрицу размером `NxM`, заполненную "спиралью":

![image.png](attachment:image.png)

Умножьте каждую строку получившейся матрицы на номер строки, выведите результат.

In [68]:
import numpy as np
n, m = map(int, input().split())
a = np.zeros((n,m))
a[0][0] = 1
y = 0
x = 0
z = 1
k =0
while k < 3:
    while x <m-1:
        x += 1
        if a[y][x] == 0:
            z += 1
            a[y][x] = z
        else:
            break
    while y < n-1:
        y += 1
        if a[y][x] == 0:
            z += 1
            a[y][x] = z
        else:
            break
    while x > 0:
        x -= 1
        if a[y][x] == 0:
            z += 1
            a[y][x] = z
        else:
            break
    while y > 0:
        y -= 1
        if a[y][x] == 0:
            z += 1
            a[y][x] = z
        else:
            y += 1
            break
    k += 1
print('спираль')
print(a)
for i in range(len(a)):
    a[i] = a[i]*i
print('ответ')
print(a)

 3 6


спираль
[[ 1.  2.  3.  4.  5.  6.]
 [14. 15. 16. 17. 18.  7.]
 [13. 12. 11. 10.  9.  8.]]
ответ
[[ 0.  0.  0.  0.  0.  0.]
 [14. 15. 16. 17. 18.  7.]
 [26. 24. 22. 20. 18. 16.]]


## Упражнение 6

Напишите функцию, считающую коэффициенты МНК для набора измерений `x` и `y`.

In [ ]:
import numpy as np  
  
def f(x, y):   
    x = np.array(x)  
    y = np.array(y)  
    n = len(x)  
    sum_x = np.sum(x)  
    sum_y = np.sum(y)  
    sum_xy = np.sum(x * y)  
    sum_x2 = np.sum(x**2)  
    slope = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x**2)  
    intercept = (sum_y - slope * sum_x) / n  
    return slope, intercept  
#apprecation Yandex Alice

### Упражнение 7

Напишите функцию, решающую линейную систему уравнений, заданную расширенной матрицей. На вход подаются `N` и `M` -- количество строк и столбцов расширенной матрицы, далее вводятся `N` строк, каждая из которых содержит `M` чисел.

In [6]:
import numpy as np

def f(N, M):
    a = []
    for i in range(N):
        row_str = input().split()
        row = [float(x) for x in row_str]
        a.append(row)
    b = []
    for i in range(len(a)):
        b.append(a[i][-1])
        a[i].pop()
    a = np.array(a)
    b = np.array(b)
    print(np.linalg.solve(a, b))

n, m = map(int, input().split())
print(f(n, m))
#apprecations Yandex, Gemini, Sasha Tiuov

 2 3
 2 3 7
 1 -1 1


[2. 1.]
None


### Упражнение 8* (для осн и продв)

Реализуйте функцию, генерирующую набор данных размером `N`, которые методом МНК аппроксимируются прямой с коэффициентами `a` и `b`. Для этого вам пригодится библиотека `random` и функция `random.gauss()`.

In [17]:
import random
import numpy as np
def f(N, a, b, noise_std):
    x_values = np.array([])
    y_values = np.array([])
    for i in range(N):
        x = random.uniform(0, 10)
        y_true = a * x + b
        noise = random.gauss(0, noise_std)
        y_noisy = y_true + noise
        np.append(x_values, x)
        np.append(y_values, y_noisy)
    z = x_values + y_values
    return z
#apprecations Gemini, но код как будто не работает, не понимою почему , Gemini изначально вообще фигню написал, пришлось менять почти все

[]


## *Функция eval()

В Python есть встроенная функция `eval()`, которая выполняет строку с
кодом и возвращает результат выполнения:

``` python
>>> eval("2 + 3*len('banana')")
20
```

Это очень мощная, но и довольно небезопасная команда.
Например, если строкой, которую мы передадим в `eval()`, окажется
`"os.system('rm -rf /')"` (в терминале Linux), то интерпретатор начнет удалять все файлы, включая системные, с компьютера.

## *Задачи по numpy для дополнительного изучения
https://github.com/rougier/numpy-100

In [1]:
print(1)

1
